[build]
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "22"
  REACT_APP_SCRIPT_URL = "https://script.google.com/macros/s/AKfycby9lM1TjcaWNXXV2i0mrhGjhIGj0K7H_ElQQGYtiNhRq3eXfiQrOzcttZG7HXn0nnGA/exec"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200